List<Map<String, dynamic>> dummyAksesMenuMarketing = [
  {
    "id_akses": "MMRKT00001",
    "nama_menu": "Agensi",
    "type": "ENT",
    "module": "MRKT",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MMRKT00002",
    "nama_menu": "Jadwal",
    "type": "ENT",
    "module": "MRKT",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MMRKT00003",
    "nama_menu": "Pemberangkatan",
    "type": "ENT",
    "module": "MRKT",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MMRKT00004",
    "nama_menu": "Tourleader",
    "type": "ENT",
    "module": "MRKT",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MMRKT00005",
    "nama_menu": "Tourleader",
    "type": "ENT",
    "module": "MRKT",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MMRKT00006",
    "nama_menu": "Master Transit",
    "type": "ENT",
    "module": "MRKT",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MMRKT00007",
    "nama_menu": "Master Maskapai",
    "type": "ENT",
    "module": "MRKT",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MMRKT00008",
    "nama_menu": "Master Hotel",
    "type": "ENT",
    "module": "MRKT",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MJAM00001",
    "nama_menu": "Calon Jamaah",
    "type": "ENT",
    "module": "JMAH",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MJAM00002",
    "nama_menu": "Pendaftaran Paket",
    "type": "ENT",
    "module": "JMAH",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MJAM00003",
    "nama_menu": "Daftar Jamaah",
    "type": "ENT",
    "module": "JMAH",
    "auth_query": false,
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
];

List<Map<String, dynamic>> dummyListUserGrup = [
  {
    "id_user": "USR00001",
    "nama_user": "Tintin",
    "keterangan": "Aktif",
    "login": "02-03-2023 15:03:00",
  },
  {
    "id_user": "USR00002",
    "nama_user": "Pujan Darmawan",
    "keterangan": "Aktif",
    "login": "02-03-2023 16:23:00",
  },
  {
    "id_user": "USR00003",
    "nama_user": "Ramdani Gunawan",
    "keterangan": "Aktif",
    "login": "01-03-2023 08:25:11",
  },
  {
    "id_user": "USR00004",
    "nama_user": "Cahaya Raudhah",
    "keterangan": "Aktif",
    "login": "03-03-2023 07:44:11",
  },
];

List<Map<String, dynamic>> dummyAksesEditMenuMarketing = [
  {
    "id_akses": "MMRKT00001",
    "nama_menu": "Agensi",
    "type": "ENT",
    "module": "MRKT",
    "auth_add": true,
    "auth_edit": true,
    "auth_delete": true,
    "auth_print": true,
    "auth_export": true,
    "cek_row": true,
  },
  {
    "id_akses": "MMRKT00002",
    "nama_menu": "Jadwal",
    "type": "ENT",
    "module": "MRKT",
    "auth_add": true,
    "auth_edit": true,
    "auth_delete": true,
    "auth_print": true,
    "auth_export": true,
    "cek_row": true,
  },
  {
    "id_akses": "MMRKT00003",
    "nama_menu": "Pemberangkatan",
    "type": "ENT",
    "module": "MRKT",
    "auth_add": true,
    "auth_edit": true,
    "auth_delete": true,
    "auth_print": true,
    "auth_export": true,
    "cek_row": true,
  },
  {
    "id_akses": "MMRKT00004",
    "nama_menu": "Tourleader",
    "type": "ENT",
    "module": "MRKT",
    "auth_add": true,
    "auth_edit": true,
    "auth_delete": true,
    "auth_print": true,
    "auth_export": true,
    "cek_row": true,
  },
  {
    "id_akses": "MMRKT00005",
    "nama_menu": "Tourleader",
    "type": "ENT",
    "module": "MRKT",
    "auth_add": true,
    "auth_edit": true,
    "auth_delete": true,
    "auth_print": true,
    "auth_export": true,
    "cek_row": true,
  },
  {
    "id_akses": "MMRKT00006",
    "nama_menu": "Master Transit",
    "type": "ENT",
    "module": "MRKT",
    "auth_add": true,
    "auth_edit": true,
    "auth_delete": true,
    "auth_print": true,
    "auth_export": true,
    "cek_row": true,
  },
  {
    "id_akses": "MMRKT00007",
    "nama_menu": "Master Maskapai",
    "type": "ENT",
    "module": "MRKT",
    "auth_add": true,
    "auth_edit": true,
    "auth_delete": true,
    "auth_print": true,
    "auth_export": true,
    "cek_row": true,
  },
  {
    "id_akses": "MMRKT00008",
    "nama_menu": "Master Hotel",
    "type": "ENT",
    "module": "MRKT",
    "auth_add": true,
    "auth_edit": true,
    "auth_delete": true,
    "auth_print": true,
    "auth_export": true,
    "cek_row": true,
  },
  {
    "id_akses": "MJAM00001",
    "nama_menu": "Calon Jamaah",
    "type": "ENT",
    "module": "JMAH",
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MJAM00002",
    "nama_menu": "Pendaftaran Paket",
    "type": "ENT",
    "module": "JMAH",
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
  {
    "id_akses": "MJAM00003",
    "nama_menu": "Daftar Jamaah",
    "type": "ENT",
    "module": "JMAH",
    "auth_add": false,
    "auth_edit": false,
    "auth_delete": false,
    "auth_print": false,
    "auth_export": false,
    "cek_row": false,
  },
];
